# The URL the site will be built for
base_url = "https://colinkiama.com"

# The site title and description; used in feeds by default.
title = "Colin Kiama"
description = "Welcome to the blog!"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

feed_filenames = ["rss.xml"]

# Syntax highlighting configuration (optional)
[markdown.highlighting]

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "class"

# 2. If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting page for the possible choices.
light_theme = "Monokai Light"
dark_theme = "Monokai Dark Soda"

extra_themes = [
  "highlight_themes/monokai-light.json",
  "highlight_themes/monokai-dark-soda.json",
]

[extra]
# Put all your custom variables here
favicon_link = "https://ik.imagekit.io/mune/mune-favicon_BOoehMPQtVAo.png"
webring_slug = "colinkiama"
portrait = "https://ik.imagekit.io/mune/mune-portrait_2Uy7ATEsei_PG.jpeg?tr=w-24,h-24"

[extra.socials]
email = "mailto:colinkiama@gmail.com"
twitter = "https://twitter.com/colinkiama"
linkedin = "https://www.linkedin.com/in/colin-kiama-11962988/"
mastodon = "https://merveilles.town/@colinkiama"
product_hunt = "https://www.producthunt.com/@colinkiama"
dev_to = "https://dev.to/colinkiama"
github = "https://www.github.com/colinkiama"
itch_io = "https://colinkiama.itch.io"
twitch = "https://www.twitch.tv/colinkiama7"
instagram = "https://instagram.com/kiam.7"
bluesky = "https://bsky.app/profile/colinkiama.bsky.social"

[extra.blog]
email = "colinkiama@gmail.com"

[extra.newsletter]
buttondown = "https://buttondown.email/colinkiama?utm_source=colinkiama.com"
buttondown_rss = "https://buttondown.email/colinkiama/rss"
substack = "https://colinkiama.substack.com?utm_source=colinkiama.com"
medium = "https://medium.com/@colinkiama?utm_source=colinkiama.com"
